"""Configuration dataclasses for the MerXen pipeline.

All pipeline parameters are defined here as Pydantic models. Configuration
is loaded from JSON files (generated by Nextflow) and validated at startup.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any, Literal

from pydantic import BaseModel, Field, field_validator, model_validator
from pydantic_settings import BaseSettings


class CellposeConfig(BaseModel):
    """Parameters for Cellpose segmentation."""

    model_type: str = "cyto3"
    gpu: bool = True
    diameter: float | None = None
    flow_threshold: float = 0.8
    cellprob_threshold: float = -5.0
    tile_overlap: float = 0.15
    bsize: int = 256
    factor_rescale: float = 1.0
    use_bfloat16: bool = True

    @field_validator("factor_rescale")
    @classmethod
    def _validate_rescale(cls: type[CellposeConfig], v: float) -> float:
        if abs(v - 1.0) > 1e-12:
            msg = (
                "MerXen is configured for native-resolution tiled Cellpose only. "
                f"Got factor_rescale={v}. Must be 1.0."
            )
            raise ValueError(msg)
        return v


class MaskFilterConfig(BaseModel):
    """Parameters for post-segmentation mask filtering."""

    max_eccentricity: float = 0.99
    min_area_percentile: float = 1.0
    min_area_px: float | None = None
    final_min_area_um2: float | None = 5.0
    final_max_area_um2: float | None = 400.0
    final_filter_chunk_mb: int = 256
    n_jobs: int = 16
    show_progress: bool = True

    @field_validator("final_min_area_um2", "final_max_area_um2")
    @classmethod
    def _validate_optional_area(
        cls: type[MaskFilterConfig],
        v: float | None,
    ) -> float | None:
        if v is not None and v < 0:
            raise ValueError("area thresholds must be non-negative")
        return v

    @field_validator("final_filter_chunk_mb")
    @classmethod
    def _validate_filter_chunk_mb(cls: type[MaskFilterConfig], v: int) -> int:
        if int(v) <= 0:
            raise ValueError("final_filter_chunk_mb must be positive")
        return int(v)

    @model_validator(mode="after")
    def _validate_area_bounds(self: MaskFilterConfig) -> MaskFilterConfig:
        if (
            self.final_min_area_um2 is not None
            and self.final_max_area_um2 is not None
            and self.final_min_area_um2 > self.final_max_area_um2
        ):
            raise ValueError("final_min_area_um2 must be <= final_max_area_um2")
        return self


class TilingConfig(BaseModel):
    """Parameters for memory-adaptive Cellpose tiling."""

    model_config = {"populate_by_name": True}

    tile_size_candidates: list[int] = Field(
        default_factory=lambda: [6144, 4096, 3072, 2048]
    )
    stitch_overlap_px: int = Field(default=256, alias="tile_overlap")
    min_tile_size: int = 1024
    status_every_tiles: int = 10
    filter_per_tile: bool = True
    duplicate_iou_threshold: float = 0.25
    duplicate_overlap_fraction: float = 0.5
    min_remaining_fraction: float = 0.05
    edge_touch_policy: Literal["keep", "skip"] = "keep"
    write_stitching_stats: bool = True

    @field_validator("tile_size_candidates")
    @classmethod
    def _validate_tile_size_candidates(
        cls: type[TilingConfig], v: list[int]
    ) -> list[int]:
        values = [int(x) for x in v]
        if not values:
            raise ValueError("tile_size_candidates must not be empty")
        if any(x <= 0 for x in values):
            raise ValueError("tile_size_candidates values must be positive")
        return values

    @field_validator("stitch_overlap_px")
    @classmethod
    def _validate_stitch_overlap_px(cls: type[TilingConfig], v: int) -> int:
        if int(v) < 0:
            raise ValueError("stitch_overlap_px must be non-negative")
        return int(v)

    @field_validator("min_tile_size", "status_every_tiles")
    @classmethod
    def _validate_positive_int(cls: type[TilingConfig], v: int) -> int:
        if int(v) <= 0:
            raise ValueError("tiling integer parameters must be positive")
        return int(v)

    @field_validator(
        "duplicate_iou_threshold",
        "duplicate_overlap_fraction",
        "min_remaining_fraction",
    )
    @classmethod
    def _validate_fraction(cls: type[TilingConfig], v: float) -> float:
        value = float(v)
        if value < 0.0 or value > 1.0:
            raise ValueError("tiling fraction parameters must be between 0 and 1")
        return value

    @model_validator(mode="after")
    def _validate_core_size(self: TilingConfig) -> TilingConfig:
        valid_candidates = [
            x for x in self.tile_size_candidates if x >= int(self.min_tile_size)
        ]
        if not valid_candidates:
            raise ValueError(
                "tile_size_candidates must include at least one value >= min_tile_size"
            )
        for tile_size in valid_candidates:
            if int(tile_size) - (2 * int(self.stitch_overlap_px)) > 0:
                return self
        raise ValueError(
            "At least one tile_size_candidate must be larger than 2 * stitch_overlap_px"
        )


class ProsegConfig(BaseModel):
    """Parameters for ProSeg transcript-based segmentation refinement."""

    binary_path: Path = Path("/usr/bin/proseg")
    samples: int = 1200
    voxel_size: float = 0.5
    burnin_voxel_size: float = 1.0
    nuclear_reassignment_prob: float = 0.2
    diffusion_probability: float = 0.2
    cell_compactness: float = 0.04
    expand_initialized_cells: int = 0
    prior_seg_reassignment_prob: float = 0.2
    use_cell_initialization: bool = True
    max_transcript_nucleus_distance: float = 60.0
    diffusion_sigma_far: float | None = None
    num_threads: int = 64
    voxel_layers: int = 2


class ProsegHybridConfig(BaseModel):
    """Transcript-supported post-processing of Cellpose and Proseg results."""

    enabled: bool = True
    min_transcripts: int = Field(default=10, ge=3)
    outlier_neighbors: int = Field(default=2, ge=1)
    outlier_mad_multiplier: float = Field(default=2.0, gt=0.0)
    minimum_external_group: int = Field(default=3, ge=2)
    chain_radius_scale: float = Field(default=2.0, gt=0.0)
    near_surface_radius_fraction: float = Field(default=0.25, ge=0.0)
    maximum_expansion_radius_fraction: float = Field(default=1.0, gt=0.0)
    attachment_arc_width_scale: float = Field(default=0.5, gt=0.0)
    rounding_radius_fraction: float = Field(default=0.15, ge=0.0)
    smoothing_radius_um: float = Field(default=10.0, ge=0.0)
    outward_rounding_um: float = Field(default=0.2, ge=0.0)
    smoothing_quad_segs: int = Field(default=32, ge=8)
    containment_tolerance_um: float = Field(default=1.0e-5, gt=0.0)


class MemoryConfig(BaseModel):
    """Memory management parameters."""

    max_system_ram_gb: float = 600.0
    memory_warn_gb: float = 560.0
    memory_check_every_chunks: int = 5
    transcript_chunk_rows: int = 1_000_000
    transcript_status_every_chunks: int = 5


class MerscopeBuildConfig(BaseModel):
    """Options for constructing a MERSCOPE SpatialData object."""

    z_layers: list[int] | None = None
    region_name: str | None = None
    slide_name: str | None = None


class XeniumBuildConfig(BaseModel):
    """Options for constructing a Xenium SpatialData object."""

    cells_boundaries: bool = True
    nucleus_boundaries: bool = True
    cells_as_circles: bool = False
    cells_labels: bool = True
    nucleus_labels: bool = True
    transcripts: bool = True
    morphology_mip: bool = False
    morphology_focus: bool = True
    aligned_images: bool = False
    cells_table: bool = True


class SpatialDataBuildConfig(BaseModel):
    """Configuration for the raw-input to SpatialData build step."""

    dataset_name: str
    platform: Literal["MERSCOPE", "XENIUM"]
    input_path: Path
    output_path: Path
    persistent_output_path: Path | None = None
    merscope_transform_path: Path | None = None
    xenium_spec_path: Path | None = None
    merscope: MerscopeBuildConfig = MerscopeBuildConfig()
    xenium: XeniumBuildConfig = XeniumBuildConfig()


class DatasetConfig(BaseModel):
    """Configuration for a single dataset (one half of a pair)."""

    name: str
    platform: Literal["MERSCOPE", "XENIUM"]
    data_path: Path
    channels: list[str]
    output_dir: Path
    persistent_latest_zarr_path: Path | None = None
    persistent_mask_path: Path | None = None
    persistent_cellpose_cellprob_path: Path | None = None
    persistent_transcripts_path: Path | None = None
    persistent_cellpose_stitching_stats_path: Path | None = None
    persistent_nuclei_mask_path: Path | None = None
    persistent_nuclei_stitching_stats_path: Path | None = None

    # MERSCOPE-specific
    image_prefix: str | None = None
    z_range: tuple[int, int] | None = None
    transform_path: Path | None = None

    # Xenium-specific
    xenium_spec_path: Path | None = None
    min_qv: float | None = None
    proseg_overrides: dict[str, Any] = Field(default_factory=dict)


class SegmentationConfig(BaseModel):
    """Full configuration for the segmentation step."""

    dataset: DatasetConfig
    cellpose: CellposeConfig = CellposeConfig()
    nuclei_cellpose: CellposeConfig = CellposeConfig(model_type="nuclei")
    mask_filter: MaskFilterConfig = MaskFilterConfig()
    nuclei_mask_filter: MaskFilterConfig = MaskFilterConfig()
    tiling: TilingConfig = TilingConfig()
    proseg: ProsegConfig = ProsegConfig()
    proseg_hybrid: ProsegHybridConfig = ProsegHybridConfig()
    memory: MemoryConfig = MemoryConfig()


class EnrichmentConfig(BaseModel):
    """Configuration for the SpatialData enrichment step."""

    dataset_name: str
    platform: Literal["MERSCOPE", "XENIUM"]
    latest_zarr_path: Path
    mask_path: Path
    nuclei_mask_path: Path
    original_data_path: Path
    output_dir: Path
    persistent_output_path: Path | None = None
    transform_path: Path | None = None


class ViewerCacheConfig(BaseModel):
    """Configuration for pre-building the napari viewer's derived caches.

    Runs after enrichment and materializes the label masks, label/outline
    pyramids, and image pyramid the comparison viewer would otherwise build on
    the fly. Parameter defaults mirror the viewer's own defaults; expose them via
    Nextflow params to keep them in lockstep with the viewer's runtime settings.
    """

    dataset_name: str
    platform: Literal["MERSCOPE", "XENIUM"]
    latest_zarr_path: Path
    original_data_path: Path
    output_dir: Path
    transform_path: Path | None = None
    downsample: int = Field(default=4, ge=2)
    label_chunk_size: int = Field(default=2048, gt=0)
    contour_width: int = Field(default=1, ge=0)
    min_size: int = Field(default=1024, gt=0)
    shape_keys: list[str] | None = None
    build_image_pyramid: bool = True


class MaskImageQuantificationConfig(BaseModel):
    """Configuration for Cellpose-mask image-channel quantification."""

    dataset_name: str
    platform: Literal["MERSCOPE", "XENIUM"]
    latest_zarr_path: Path
    mask_path: Path
    output_dir: Path
    table_key: str = "table_MOSAIK_cellpose_image_quantification"
    shape_key: str = "MOSAIK_cellpose"
    tile_size: int = 2048

    @field_validator("tile_size")
    @classmethod
    def _validate_tile_size(
        cls: type[MaskImageQuantificationConfig],
        value: int,
    ) -> int:
        if int(value) <= 0:
            raise ValueError("tile_size must be positive")
        return int(value)


class QCConfig(BaseModel):
    """Configuration for QC metric computation."""

    dataset_name: str
    latest_zarr_path: Path
    output_dir: Path
    table_key: str | None = None
    shape_key: str | None = None


class CorticalDepthTableConfig(BaseModel):
    """One cell table to annotate with cortical-depth coordinates."""

    segmentation: str
    table_key: str
    shape_key: str | None = None


class CorticalDepthConfig(BaseModel):
    """Configuration for cortical-depth coordinate computation."""

    dataset_name: str
    platform: Literal["MERSCOPE", "XENIUM"]
    latest_zarr_path: Path
    output_dir: Path
    tables: list[CorticalDepthTableConfig]
    pial_boundary_path: Path | None = None
    wm_boundary_path: Path | None = None
    side_boundary_path: Path | None = None
    exclusion_path: Path | None = None
    ribbon_path: Path | None = None
    annotation_path: Path | None = None
    coordinate_unit_um: float = Field(default=1.0, gt=0.0)
    raster_resolution_um: float = Field(default=5.0, gt=0.0)
    raster_padding_um: float | None = Field(default=None, gt=0.0)
    boundary_band_um: float | None = Field(default=None, gt=0.0)
    boundary_smoothing_window: int = Field(default=0, ge=0)
    streamline_spacing_um: float = Field(default=50.0, gt=0.0)
    streamline_step_um: float | None = Field(default=None, gt=0.0)
    streamline_max_steps: int = Field(default=4000, ge=1)
    streamline_resample_points: int = Field(default=101, ge=2)
    side_boundary_distance_um: float = Field(default=25.0, ge=0.0)
    n_jobs: int | None = Field(default=None, ge=1)
    contour_levels: list[float] = Field(
        default_factory=lambda: [round(i / 10.0, 1) for i in range(1, 10)]
    )
    write_spatialdata_table: bool = True

    @field_validator("contour_levels")
    @classmethod
    def _validate_contour_levels(
        cls: type[CorticalDepthConfig],
        values: list[float],
    ) -> list[float]:
        levels = [float(value) for value in values]
        if not levels:
            raise ValueError("contour_levels must not be empty")
        if any(value <= 0.0 or value >= 1.0 for value in levels):
            raise ValueError("contour_levels must be strictly between 0 and 1")
        return sorted(set(levels))

    @model_validator(mode="after")
    def _validate_annotation_inputs(self: CorticalDepthConfig) -> CorticalDepthConfig:
        if not self.tables:
            raise ValueError("CorticalDepthConfig requires at least one table")
        if self.annotation_path is None and self.pial_boundary_path is None:
            raise ValueError(
                "Provide pial_boundary_path, or a combined annotation_path containing "
                "role-labelled cortical-depth annotations"
            )
        return self


class DistanceFromObjectTableConfig(BaseModel):
    """One cell table to annotate with distances from polygon objects."""

    segmentation: str
    table_key: str
    shape_key: str | None = None


class DistanceFromObjectConfig(BaseModel):
    """Configuration for per-sample distance-from-object annotation."""

    pair_id: str
    dataset_name: str
    platform: Literal["MERSCOPE", "XENIUM"]
    latest_zarr_path: Path
    output_dir: Path
    object_annotation_path: Path
    tables: list[DistanceFromObjectTableConfig]
    object_types: list[str] | None = None
    coordinate_unit_um: float = Field(default=1.0, gt=0.0)
    near_distance_um: float = Field(default=50.0, ge=0.0)
    far_distance_um: float = Field(default=100.0, ge=0.0)
    max_distance_um: float = Field(default=200.0, gt=0.0)
    tissue_annotation_column: str = "cortical_depth_annotation"
    included_tissue_annotations: list[str] = Field(
        default_factory=lambda: ["grey_matter"]
    )
    min_cells_per_pseudobulk: int = Field(default=10, ge=1)
    write_spatialdata_table: bool = True

    @field_validator("object_types", "included_tissue_annotations")
    @classmethod
    def _validate_nonempty_strings(
        cls: type[DistanceFromObjectConfig],
        values: list[str] | None,
    ) -> list[str] | None:
        if values is None:
            return None
        cleaned = [str(value).strip() for value in values if str(value).strip()]
        if not cleaned:
            raise ValueError("Configured annotation lists must not be empty")
        return list(dict.fromkeys(cleaned))

    @model_validator(mode="after")
    def _validate_distance_bands(
        self: DistanceFromObjectConfig,
    ) -> DistanceFromObjectConfig:
        if not self.tables:
            raise ValueError("DistanceFromObjectConfig requires at least one table")
        if self.near_distance_um >= self.far_distance_um:
            raise ValueError("near_distance_um must be less than far_distance_um")
        if self.far_distance_um >= self.max_distance_um:
            raise ValueError("far_distance_um must be less than max_distance_um")
        return self


class DistanceFromObjectCohortConfig(BaseModel):
    """Configuration for cohort-level paired near-vs-far analysis."""

    platform: Literal["MERSCOPE", "XENIUM"]
    annotation_output_dirs: list[Path]
    output_dir: Path
    segmentations: list[str]
    min_pairs: int = Field(default=2, ge=2)
    n_cpus: int | None = Field(default=None, ge=1)

    @field_validator("annotation_output_dirs", "segmentations")
    @classmethod
    def _validate_required_lists(
        cls: type[DistanceFromObjectCohortConfig],
        values: list[Any],
    ) -> list[Any]:
        if not values:
            raise ValueError("Cohort analysis lists must not be empty")
        return values


class LegacySpateoAlignmentConfig(BaseModel):
    """Legacy Spateo registration parameters for paired-section alignment."""

    model_config = {"populate_by_name": True}

    mode: str = "SN-S"
    device: str = "auto"
    dtype: str = "float32"
    max_iter: int = 360
    nonrigid_start_iter: int = 220
    beta: float = 0.005
    lambda_vf: float = Field(default=3000.0, alias="lambdaVF")
    k: int = Field(default=15, alias="K")
    partial_robust_level: int = 100
    allow_flip: bool = True
    SVI_mode: bool = False
    n_sampling: int = 1_000
    sparse_top_k: int = 512
    sparse_calculation_mode: bool = True
    use_chunk: bool = True
    chunk_capacity: int = 1
    normalize_total: float = 10_000.0
    log1p: bool = True
    use_hvg: bool = False
    n_top_genes: int = 100
    use_pca: bool = True
    n_pcs: int = 50
    max_alignment_cells: int | None = 35_000
    alignment_seed: int = 21
    include_image_features: bool = True
    selected_mode: Literal["rigid", "nonrigid"] = "nonrigid"
    rbf_neighbors: int = 64
    rbf_smoothing: float = 0.0
    max_nonrigid_anchors: int = 5_000
    tune: bool = False
    param_grid: list[dict[str, Any]] = Field(default_factory=list)


class AlignmentImageConfig(BaseModel):
    """DAPI image and coordinate metadata for one alignment platform."""

    image_key: str | None = None
    image_path: Path | None = None
    tissue_annotation_path: Path | None = None
    dapi_channel: str = "DAPI"
    pixel_size_um: float | None = Field(default=None, gt=0.0)
    dataset_to_image_matrix: list[list[float]] | None = None

    @field_validator("dataset_to_image_matrix")
    @classmethod
    def _validate_dataset_to_image_matrix(
        cls: type[AlignmentImageConfig],
        value: list[list[float]] | None,
    ) -> list[list[float]] | None:
        if value is None:
            return None
        if len(value) != 3 or any(len(row) != 3 for row in value):
            raise ValueError("dataset_to_image_matrix must be a 3x3 matrix")
        return [[float(item) for item in row] for row in value]


class DAPIProcessingConfig(BaseModel):
    """Physical-unit DAPI preprocessing and legacy mask parameters."""

    background_sigma_um: float = Field(default=75.0, gt=0.0)
    background_boundary_mode: Literal["mirror", "reflect", "nearest"] = "mirror"
    lower_percentile: float = Field(default=0.5, ge=0.0, lt=100.0)
    upper_percentile: float = Field(default=99.5, gt=0.0, le=100.0)
    compression: Literal["log1p", "asinh"] = "asinh"
    clahe_clip_limit: float = Field(default=0.01, gt=0.0)
    smoothing_sigma_um: float = Field(default=3.0, ge=0.0)
    edge_taper_um: float = Field(default=150.0, ge=0.0)
    edge_exclusion_um: float = Field(default=150.0, ge=0.0)
    mask_downsample: int = Field(default=4, ge=1)
    mask_smoothing_sigma_um: float = Field(default=20.0, gt=0.0)
    mask_closing_radius_um: float = Field(default=30.0, ge=0.0)
    mask_min_area_um2: float = Field(default=25_000.0, ge=0.0)
    mask_hole_area_um2: float = Field(default=25_000.0, ge=0.0)
    mask_dilation_um: float = Field(default=10.0, ge=0.0)

    @model_validator(mode="after")
    def _validate_percentiles(self: DAPIProcessingConfig) -> DAPIProcessingConfig:
        if self.lower_percentile >= self.upper_percentile:
            raise ValueError("lower_percentile must be less than upper_percentile")
        return self


class OrientationSearchConfig(BaseModel):
    """Coarse arbitrary-angle orientation estimation parameters."""

    max_dimension_px: int = Field(default=512, ge=64)
    sift_features: int = Field(default=7_500, ge=100)
    ratio_threshold: float = Field(default=0.75, gt=0.0, lt=1.0)
    ransac_threshold_px: float = Field(default=5.0, gt=0.0)
    minimum_inliers: int = Field(default=12, ge=3)
    minimum_inlier_coverage: float = Field(default=0.08, ge=0.0, le=1.0)
    minimum_dice: float = Field(default=0.08, ge=0.0, le=1.0)
    minimum_scale: float = Field(default=0.75, gt=0.0)
    maximum_scale: float = Field(default=1.35, gt=0.0)
    coarse_step_degrees: float = Field(default=10.0, gt=0.0, le=180.0)
    refine_step_degrees: float = Field(default=2.0, gt=0.0, le=90.0)
    final_step_degrees: float = Field(default=0.5, gt=0.0, le=45.0)
    candidates_to_refine: int = Field(default=4, ge=1)
    allow_reflection: bool = True
    reflection_mode: Literal["auto", "force", "forbid"] = "auto"
    reflection_minimum_score_improvement: float = Field(default=0.01, ge=0.0)
    translation_candidates_per_angle: int = Field(default=3, ge=1)
    coarse_translation_radius_px: float = Field(default=64.0, ge=0.0)
    refine_translation_radius_px: float = Field(default=16.0, ge=0.0)
    final_translation_radius_px: float = Field(default=4.0, ge=0.0)
    minimum_fixed_overlap_fraction: float = Field(default=0.45, ge=0.0, le=1.0)
    minimum_moving_overlap_fraction: float = Field(default=0.45, ge=0.0, le=1.0)
    minimum_retained_moving_fraction: float = Field(default=0.6, ge=0.0, le=1.0)
    minimum_relative_dice: float = Field(default=0.7, ge=0.0, le=1.0)
    initial_angle_degrees: float | None = None
    initial_translation_x_um: float | None = None
    initial_translation_y_um: float | None = None
    local_fine_search_enabled: bool = True
    local_fine_angle_radius_degrees: float = Field(default=2.5, gt=0.0, le=15.0)
    local_fine_translation_radius_um: float = Field(default=500.0, gt=0.0)
    local_fine_coarse_angle_step_degrees: float = Field(
        default=0.5,
        gt=0.0,
        le=5.0,
    )
    local_fine_coarse_translation_step_um: float = Field(default=100.0, gt=0.0)
    local_fine_refine_angle_step_degrees: float = Field(
        default=0.1,
        gt=0.0,
        le=1.0,
    )
    local_fine_refine_translation_step_um: float = Field(default=25.0, gt=0.0)
    local_fine_maxima_to_refine: int = Field(default=4, ge=1)
    local_fine_competing_score_margin: float = Field(default=0.002, ge=0.0)
    overlap_weight: float = Field(default=0.6, ge=0.0)
    mutual_information_weight: float = Field(default=0.4, ge=0.0)
    feature_weight: float = Field(default=0.1, ge=0.0)

    @model_validator(mode="after")
    def _validate_scale_range(
        self: OrientationSearchConfig,
    ) -> OrientationSearchConfig:
        if self.minimum_scale >= self.maximum_scale:
            raise ValueError("minimum_scale must be less than maximum_scale")
        if (self.initial_translation_x_um is None) != (
            self.initial_translation_y_um is None
        ):
            raise ValueError(
                "initial_translation_x_um and initial_translation_y_um "
                "must be set together"
            )
        if self.overlap_weight + self.mutual_information_weight <= 0:
            raise ValueError("orientation Dice and NMI weights cannot both be zero")
        if (
            self.local_fine_refine_angle_step_degrees
            > self.local_fine_coarse_angle_step_degrees
        ):
            raise ValueError(
                "local fine refine angle step cannot exceed the coarse angle step"
            )
        if (
            self.local_fine_refine_translation_step_um
            > self.local_fine_coarse_translation_step_um
        ):
            raise ValueError(
                "local fine refine translation step cannot exceed the coarse "
                "translation step"
            )
        return self


class PartialOverlapRigidConfig(BaseModel):
    """Partial-overlap-aware rigid refinement after coarse pre-orientation."""

    enabled: bool = True
    max_dimension_px: int = Field(default=512, ge=128)
    angle_search_radius_degrees: float = Field(default=10.0, gt=0.0, le=45.0)
    coarse_angle_step_degrees: float = Field(default=1.0, gt=0.0, le=10.0)
    maximum_translation_um: float = Field(default=1_500.0, gt=0.0)
    retained_boundary_fraction: float = Field(default=0.7, gt=0.0, le=1.0)
    boundary_distance_scale_um: float = Field(default=150.0, gt=0.0)
    density_sigma_um: float = Field(default=75.0, gt=0.0)
    minimum_fixed_overlap_fraction: float = Field(
        default=0.45,
        ge=0.0,
        le=1.0,
    )
    minimum_moving_overlap_fraction: float = Field(
        default=0.45,
        ge=0.0,
        le=1.0,
    )
    boundary_weight: float = Field(default=0.65, ge=0.0)
    density_weight: float = Field(default=0.35, ge=0.0)
    overlap_penalty_weight: float = Field(default=2.0, ge=0.0)
    candidates_to_refine: int = Field(default=5, ge=1, le=20)
    optimizer_max_iterations: int = Field(default=80, ge=1)
    minimum_score_improvement: float = Field(default=0.002, ge=0.0)
    ambiguity_score_margin: float = Field(default=0.01, ge=0.0)

    @model_validator(mode="after")
    def _validate_objective_weights(
        self: PartialOverlapRigidConfig,
    ) -> PartialOverlapRigidConfig:
        if self.boundary_weight + self.density_weight <= 0:
            raise ValueError(
                "At least one partial-overlap objective weight must be positive"
            )
        return self


class ValisFeatureConfig(BaseModel):
    """VALIS learned feature-detector and matcher parameters."""

    detector: Literal["disk"] = "disk"
    matcher: Literal["lightglue"] = "lightglue"
    num_features: int = Field(default=7_500, ge=100)
    device: str = "auto"
    ransac_threshold_px: float = Field(default=5.0, gt=0.0)


class ValisNonRigidConfig(BaseModel):
    """Conservative optional VALIS non-rigid registration parameters."""

    enabled: bool = True
    backend: Literal["optical_flow", "simple_elastix"] = "optical_flow"
    compose_non_rigid: bool = False
    grid_spacing_ratio: float = Field(default=0.08, gt=0.0, le=0.5)
    maximum_iterations: int = Field(default=500, ge=1)
    smoothing_sigma_ratio: float = Field(default=0.02, ge=0.0, le=0.5)
    field_sample_spacing_px: int = Field(default=8, ge=1)


class AlignmentQCThresholds(BaseModel):
    """Configurable global and non-rigid registration acceptance thresholds."""

    minimum_global_dice: float = Field(default=0.15, ge=0.0, le=1.0)
    minimum_global_mutual_information: float = Field(default=0.02, ge=0.0)
    minimum_global_inliers: int = Field(default=8, ge=0)
    minimum_inlier_coverage: float = Field(default=0.05, ge=0.0, le=1.0)
    affine_minimum_determinant: float = Field(default=0.25, gt=0.0)
    affine_maximum_determinant: float = Field(default=4.0, gt=0.0)
    affine_minimum_singular_value: float = Field(default=0.5, gt=0.0)
    affine_maximum_singular_value: float = Field(default=2.0, gt=0.0)
    affine_maximum_shear: float = Field(default=0.5, ge=0.0)
    rigid_maximum_determinant_deviation: float = Field(default=0.002, ge=0.0)
    rigid_maximum_singular_value_deviation: float = Field(default=0.001, ge=0.0)
    rigid_maximum_shear: float = Field(default=0.001, ge=0.0)
    morphology_fallback_enabled: bool = True
    morphology_minimum_global_dice: float = Field(default=0.65, ge=0.0, le=1.0)
    morphology_minimum_global_iou: float = Field(default=0.5, ge=0.0, le=1.0)
    morphology_minimum_density_correlation: float = Field(
        default=0.15,
        ge=-1.0,
        le=1.0,
    )
    morphology_minimum_overlap_fraction: float = Field(
        default=0.6,
        ge=0.0,
        le=1.0,
    )
    morphology_maximum_dice_degradation: float = Field(
        default=0.05,
        ge=0.0,
        le=1.0,
    )
    morphology_affine_minimum_singular_value: float = Field(default=0.7, gt=0.0)
    morphology_affine_maximum_singular_value: float = Field(default=1.4, gt=0.0)
    morphology_affine_maximum_shear: float = Field(default=0.25, ge=0.0)
    non_rigid_minimum_nmi_improvement: float = Field(default=0.0, ge=0.0)
    non_rigid_maximum_p95_displacement_um: float = Field(default=500.0, gt=0.0)
    non_rigid_maximum_coherent_rotation_degrees: float = Field(
        default=0.25,
        gt=0.0,
    )
    non_rigid_maximum_coherent_translation_um: float = Field(
        default=25.0,
        gt=0.0,
    )
    non_rigid_maximum_density_correlation_degradation: float = Field(
        default=0.0,
        ge=0.0,
    )
    non_rigid_maximum_robust_score_degradation: float = Field(
        default=0.002,
        ge=0.0,
    )
    non_rigid_maximum_tissue_dice_degradation: float = Field(
        default=0.01,
        ge=0.0,
        le=1.0,
    )
    non_rigid_maximum_nonpositive_jacobian_fraction: float = Field(
        default=0.001,
        ge=0.0,
        le=1.0,
    )
    non_rigid_minimum_jacobian: float = Field(default=0.2, gt=0.0)
    non_rigid_maximum_jacobian: float = Field(default=5.0, gt=0.0)


class ValisAlignmentConfig(BaseModel):
    """VALIS 1.2 DAPI-only registration parameters."""

    registration_pixel_size_um: float | None = Field(default=None, gt=0.0)
    registration_source_max_dim_px: int = Field(default=3_200, ge=256)
    canvas_padding_fraction: float = Field(default=0.15, ge=0.0, le=1.0)
    max_processed_image_dim_px: int = Field(default=1_600, ge=128)
    max_non_rigid_registration_dim_px: int = Field(default=3_200, ge=128)
    thumbnail_size: int = Field(default=1_024, ge=64)
    norm_method: Literal["img_stats", "histo_match", "none"] = "img_stats"
    # Retained so existing JSON/resume manifests remain parseable. The VALIS
    # backend now locks the accepted MerXen pretransform and does not execute a
    # second global fit.
    global_transform: Literal["rigid", "affine", "similarity"] = "rigid"
    random_seed: int = 21
    coordinate_system_name: str = "merxen_xenium"
    transform_transcripts: bool = True
    transform_centroids: bool = True
    transform_polygons: bool = True
    mark_shared_tissue_domain: bool = True
    resume: bool = True
    preprocessing: DAPIProcessingConfig = DAPIProcessingConfig()
    orientation: OrientationSearchConfig = OrientationSearchConfig()
    partial_overlap: PartialOverlapRigidConfig = PartialOverlapRigidConfig()
    features: ValisFeatureConfig = ValisFeatureConfig()
    non_rigid: ValisNonRigidConfig = ValisNonRigidConfig()
    qc: AlignmentQCThresholds = AlignmentQCThresholds()


class AlignmentConfig(BaseModel):
    """Configuration for paired DAPI alignment with a legacy Spateo option."""

    pair_id: str
    merscope_zarr_path: Path
    xenium_zarr_path: Path
    output_dir: Path
    backend: Literal["valis", "legacy_spateo"] = "valis"
    fixed_platform: Literal["XENIUM", "MERSCOPE"] = "XENIUM"
    moving_platform: Literal["XENIUM", "MERSCOPE"] = "MERSCOPE"
    write_aligned_zarrs: bool = True
    merscope_image: AlignmentImageConfig = AlignmentImageConfig()
    xenium_image: AlignmentImageConfig = AlignmentImageConfig()
    valis: ValisAlignmentConfig = ValisAlignmentConfig()
    legacy_spateo: LegacySpateoAlignmentConfig = LegacySpateoAlignmentConfig()

    @model_validator(mode="before")
    @classmethod
    def _accept_legacy_spateo_key(cls: type[AlignmentConfig], value: Any) -> Any:
        if (
            isinstance(value, dict)
            and "spateo" in value
            and "legacy_spateo" not in value
        ):
            return dict(value) | {"legacy_spateo": value["spateo"]}
        return value

    @model_validator(mode="after")
    def _validate_platform_pair(self: AlignmentConfig) -> AlignmentConfig:
        if self.fixed_platform == self.moving_platform:
            raise ValueError("fixed_platform and moving_platform must differ")
        if self.backend == "legacy_spateo" and (
            self.fixed_platform != "XENIUM" or self.moving_platform != "MERSCOPE"
        ):
            raise ValueError(
                "legacy_spateo only supports fixed_platform='XENIUM' and "
                "moving_platform='MERSCOPE'; use backend='valis' for "
                "configurable platform roles"
            )
        return self

    @property
    def spateo(self: AlignmentConfig) -> LegacySpateoAlignmentConfig:
        """Return legacy Spateo config for source compatibility."""
        return self.legacy_spateo


# Source-compatible name for callers that still construct the old config.
SpateoAlignmentConfig = LegacySpateoAlignmentConfig


class AlignmentQCConfig(BaseModel):
    """Configuration for post-alignment DAPI QC collation."""

    pair_id: str
    merscope_zarr_path: Path
    xenium_zarr_path: Path
    output_dir: Path
    transform_json_path: Path | None = None
    grid_rows: int = 10
    grid_cols: int = 10


class ComparisonConfig(BaseModel):
    """Configuration for cross-platform comparison."""

    merscope_zarr_path: Path
    xenium_zarr_path: Path
    output_dir: Path
    pair_id: str
    merscope_table_key: str | None = None
    xenium_table_key: str | None = None


class VisualizationSampleConfig(BaseModel):
    """One SpatialData sample to include in visualization output."""

    sample_id: str
    platform: Literal["MERSCOPE", "XENIUM"]
    zarr_path: Path
    segmentation: str | None = None
    table_key: str | None = None
    shape_key: str | None = None


class VisualizationConfig(BaseModel):
    """Configuration for generating plots."""

    output_dir: Path
    pair_id: str
    samples: list[VisualizationSampleConfig] = Field(default_factory=list)
    merscope_zarr_path: Path | None = None
    xenium_zarr_path: Path | None = None

    @model_validator(mode="after")
    def _populate_legacy_samples(self: VisualizationConfig) -> VisualizationConfig:
        if not self.samples:
            legacy_samples = []
            if self.merscope_zarr_path is not None:
                legacy_samples.append(
                    VisualizationSampleConfig(
                        sample_id=f"{self.pair_id}_MERSCOPE",
                        platform="MERSCOPE",
                        zarr_path=self.merscope_zarr_path,
                    )
                )
            if self.xenium_zarr_path is not None:
                legacy_samples.append(
                    VisualizationSampleConfig(
                        sample_id=f"{self.pair_id}_XENIUM",
                        platform="XENIUM",
                        zarr_path=self.xenium_zarr_path,
                    )
                )
            self.samples = legacy_samples

        if not self.samples:
            raise ValueError(
                "VisualizationConfig requires at least one sample or legacy "
                "merscope_zarr_path/xenium_zarr_path values."
            )

        seen_platforms: set[str] = set()
        for sample in self.samples:
            if sample.platform in seen_platforms:
                raise ValueError(
                    f"VisualizationConfig has duplicate platform {sample.platform!r}"
                )
            seen_platforms.add(sample.platform)

        return self


class ClusteringSquidpySampleConfig(BaseModel):
    """One SpatialData sample to cluster with Scanpy/Squidpy."""

    sample_id: str
    platform: Literal["MERSCOPE", "XENIUM"]
    zarr_path: Path
    segmentation: str | None = None
    table_key: str | None = None
    shape_key: str | None = None


class ClusteringSquidpyRoundConfig(BaseModel):
    """Per-round Scanpy/Squidpy clustering overrides.

    ``None`` values inherit the top-level ``ClusteringSquidpyConfig`` setting.
    Round-specific defaults set only the intended Leiden granularity.
    """

    min_counts: int | None = Field(default=None, ge=0)
    min_cells: int | None = Field(default=None, ge=1)
    n_pcs: int | None = Field(default=None, ge=1)
    n_neighbors: int | None = Field(default=None, ge=2)
    leiden_resolution: float = Field(default=0.5, gt=0.0)
    umap_min_dist: float | None = Field(default=None, ge=0.0)
    umap_spread: float | None = Field(default=None, gt=0.0)


class ClusteringSquidpyAnnotationConfig(BaseModel):
    """Atlas marker options for hierarchical broad-cluster annotation."""

    reference_atlas: Literal["whb", "wmb"] = "whb"
    marker_lookup_path: Path | None = None
    taxonomy_metadata_path: Path | None = None
    cluster_membership_path: Path | None = None
    reference_cache_dir: Path | None = Path("./mapmycells_cache")
    reference_gene_metadata_paths: list[Path] = Field(default_factory=list)
    marker_level: str | None = None
    min_marker_overlap: int = Field(default=3, ge=1)
    max_markers_per_label: int | None = Field(default=80, ge=1)
    score_margin_threshold: float = Field(default=0.0, ge=0.0)
    unknown_label: str = "Mixed/Unknown"

    @model_validator(mode="after")
    def _set_atlas_defaults(
        self: ClusteringSquidpyAnnotationConfig,
    ) -> ClusteringSquidpyAnnotationConfig:
        if self.marker_level is None:
            self.marker_level = (
                "CCN20230722_CLAS"
                if self.reference_atlas == "wmb"
                else "CCN202210140_SUPC"
            )
        return self


class ClusteringSquidpyConfig(BaseModel):
    """Configuration for the Squidpy/Scanpy clustering stage."""

    pair_id: str
    output_dir: Path
    samples: list[ClusteringSquidpySampleConfig]
    drop_control_features: bool = True
    min_counts: int = 10
    min_cells: int = 5
    normalize_target_sum: float | None = None
    normalize_exclude_highly_expressed: bool = False
    normalize_max_fraction: float = 0.05
    n_pcs: int = 60
    n_neighbors: int = 30
    leiden_resolution: float = 0.5
    umap_min_dist: float = 0.3
    umap_spread: float = 1.0
    random_seed: int = 0
    spatial_point_size: float = 0.5
    spatial_scatter_point_size: float = 2.0
    figure_dpi: int = 180
    use_gpu: bool = True
    write_spatialdata_table: bool = True
    hierarchical_enabled: bool = True
    broad_round: ClusteringSquidpyRoundConfig = Field(
        default_factory=lambda: ClusteringSquidpyRoundConfig(leiden_resolution=0.2)
    )
    subcluster_round: ClusteringSquidpyRoundConfig = Field(
        default_factory=lambda: ClusteringSquidpyRoundConfig(leiden_resolution=0.5)
    )
    subcluster_resolution_overrides: dict[str, float] = Field(default_factory=dict)
    neuron_split_round: ClusteringSquidpyRoundConfig = Field(
        default_factory=lambda: ClusteringSquidpyRoundConfig(leiden_resolution=0.15)
    )
    neuron_subcluster_round: ClusteringSquidpyRoundConfig = Field(
        default_factory=lambda: ClusteringSquidpyRoundConfig(leiden_resolution=0.5)
    )
    broad_annotation: ClusteringSquidpyAnnotationConfig = Field(
        default_factory=ClusteringSquidpyAnnotationConfig
    )
    min_branch_cells: int = Field(default=50, ge=1)


class MenderConfig(BaseModel):
    """Configuration for one independent MENDER acquisition."""

    pair_id: str
    sample_id: str
    platform: Literal["MERSCOPE", "XENIUM"]
    segmentation: str
    source_h5ad: Path
    source_h5ad_origin: Path | None = None
    spatialdata_path: Path
    source_spatialdata_table: str
    native_shape_key: str
    output_dir: Path
    cell_state_key: str = "hierarchical_cluster"
    missing_state_policy: Literal["error"] = "error"
    nn_mode: Literal["radius", "k", "ring"] = "radius"
    radius_um: float = Field(default=20.0, gt=0.0)
    n_scales: int = Field(default=5, ge=1)
    count_rep: Literal["s", "a"] = "s"
    include_self: bool = False
    clustering_mode: Literal["resolution", "target_k"] = "resolution"
    leiden_resolution: float = Field(default=0.8, gt=0.0)
    target_k: int | None = Field(default=None, ge=2)
    random_seed: int = 666
    run_umap: bool = True
    write_spatialdata_table: bool = True
    figure_dpi: int = Field(default=180, ge=72)

    @field_validator("cell_state_key", "source_spatialdata_table", "native_shape_key")
    @classmethod
    def _validate_required_name(cls: type[MenderConfig], value: str) -> str:
        cleaned = str(value).strip()
        if not cleaned:
            raise ValueError(
                "MENDER column and SpatialData element names must not be empty"
            )
        return cleaned

    @model_validator(mode="after")
    def _validate_clustering_request(self: MenderConfig) -> MenderConfig:
        if self.clustering_mode == "target_k" and self.target_k is None:
            raise ValueError("target_k is required when clustering_mode='target_k'")
        return self


class SpatialGeneAnalysisSampleConfig(BaseModel):
    """One SpatialData sample for per-gene spatial autocorrelation."""

    sample_id: str
    platform: Literal["MERSCOPE", "XENIUM"]
    zarr_path: Path
    segmentation: str | None = None
    table_key: str | None = None
    shape_key: str | None = None
    nuclei_shape_key: str = "cellpose_nuclei"
    pial_boundary_path: Path | None = None
    wm_boundary_path: Path | None = None
    side_boundary_path: Path | None = None
    exclusion_path: Path | None = None
    ribbon_path: Path | None = None
    annotation_path: Path | None = None


class SpatialGeneAnalysisConfig(BaseModel):
    """Configuration for per-gene Squidpy spatial autocorrelation analysis."""

    pair_id: str
    output_dir: Path
    samples: list[SpatialGeneAnalysisSampleConfig]
    drop_control_features: bool = True
    min_counts: int = Field(default=0, ge=0)
    min_cells: int = Field(default=5, ge=1)
    normalize_target_sum: float | None = None
    normalize_exclude_highly_expressed: bool = False
    normalize_max_fraction: float = 0.05
    n_neighbors: int = Field(default=6, ge=1)
    top_n: int = Field(default=10, ge=1)
    spatial_point_size: float = Field(default=2.0, gt=0)
    figure_dpi: int = Field(default=180, ge=72)
    transcript_analysis_enabled: bool = True
    transcript_min_count: int = Field(default=50, ge=2)
    paircorr_min_count: int = Field(default=100, ge=2)
    paircorr_max_transcripts_per_gene: int = Field(default=5_000, ge=10)
    paircorr_distance_edges_um: list[float] = Field(
        default_factory=lambda: [0.0, 2.0, 5.0, 20.0, 50.0, 200.0]
    )
    paircorr_permutations: int = Field(default=100, ge=1)
    paircorr_seed: int = 0
    paircorr_n_jobs: int = Field(default=1, ge=1)
    transcript_chunk_rows: int = Field(default=500_000, ge=1)
    pericellular_distance_um: float = Field(default=5.0, gt=0.0)
    membrane_distance_um: float = Field(default=2.0, gt=0.0)
    signed_distance_edges_um: list[float] = Field(
        default_factory=lambda: [
            -200.0,
            -50.0,
            -20.0,
            -5.0,
            -2.0,
            0.0,
            2.0,
            5.0,
            20.0,
            50.0,
            200.0,
        ]
    )
    transcript_diagnostic_top_n: int = Field(default=3, ge=1)
    transcript_diagnostic_max_genes: int = Field(default=30, ge=1)
    transcript_diagnostic_window_um: float = Field(default=250.0, gt=0.0)
    transcript_plot_max_points: int = Field(default=20_000, ge=100)

    @field_validator("paircorr_distance_edges_um", "signed_distance_edges_um")
    @classmethod
    def _validate_distance_edges(
        cls: type[SpatialGeneAnalysisConfig],
        values: list[float],
        info: Any,
    ) -> list[float]:
        edges = [float(value) for value in values]
        if len(edges) < 2:
            raise ValueError(f"{info.field_name} must contain at least 2 edges")
        if info.field_name == "paircorr_distance_edges_um" and edges[0] != 0.0:
            raise ValueError("paircorr_distance_edges_um must start at 0")
        if any(right <= left for left, right in zip(edges, edges[1:], strict=False)):
            raise ValueError(f"{info.field_name} must be strictly increasing")
        return edges


class MecrSampleConfig(BaseModel):
    """One SpatialData cell-count table to score with MECR."""

    sample_id: str
    platform: Literal["MERSCOPE", "XENIUM"]
    zarr_path: Path
    segmentation: str | None = None
    table_key: str | None = None


class MecrReferenceConfig(BaseModel):
    """Configuration for paper-standard WHB MECR marker discovery."""

    output_dir: Path
    samples: list[MecrSampleConfig]
    neurons_h5ad_path: Path = Path(
        "/media/mathieubo/SSD1/MerXen/mapmycells/abc_whb/"
        "expression_matrices/WHB-10Xv3/20240330/WHB-10Xv3-Neurons-raw.h5ad"
    )
    nonneurons_h5ad_path: Path = Path(
        "/media/mathieubo/SSD1/MerXen/mapmycells/abc_whb/"
        "expression_matrices/WHB-10Xv3/20240330/WHB-10Xv3-Nonneurons-raw.h5ad"
    )
    cell_metadata_path: Path = Path(
        "/media/mathieubo/SSD1/MerXen/mapmycells/abc_whb/metadata/"
        "WHB-10Xv3/20241115/cell_metadata.csv"
    )
    taxonomy_metadata_path: Path = Path(
        "/media/mathieubo/SSD1/MerXen/mapmycells/abc_whb/metadata/"
        "WHB-taxonomy/20240330/cluster_annotation_term.csv"
    )
    cluster_membership_path: Path = Path(
        "/media/mathieubo/SSD1/MerXen/mapmycells/abc_whb/metadata/"
        "WHB-taxonomy/20240330/cluster_to_cluster_annotation_membership.csv"
    )
    taxonomy_level: str = "CCN202210140_SUPC"
    gene_symbol_column: str = "gene_symbol"
    target_broad_classes: list[str] = Field(
        default_factory=lambda: [
            "Neurons",
            "Oligodendrocytes",
            "Oligodendrocyte precursors",
            "Astrocytes",
            "Microglia",
            "Fibroblasts",
            "Vascular cells",
        ]
    )
    marker_min_target_fraction: float = Field(default=0.25, ge=0.0, le=1.0)
    marker_max_other_fraction: float = Field(default=0.01, ge=0.0, le=1.0)
    normalize_target_sum: float = Field(default=10_000.0, gt=0.0)
    reference_chunk_rows: int = Field(default=5_000, ge=1)
    wilcoxon_tie_correct: bool = True
    figure_dpi: int = Field(default=180, ge=72)

    @model_validator(mode="after")
    def _validate_mecr_reference(self: MecrReferenceConfig) -> MecrReferenceConfig:
        if not self.samples:
            raise ValueError("MecrReferenceConfig requires at least one sample")
        if len(self.target_broad_classes) < 2:
            raise ValueError(
                "MECR marker discovery requires at least two broad classes"
            )
        if self.marker_min_target_fraction <= self.marker_max_other_fraction:
            raise ValueError(
                "marker_min_target_fraction must exceed marker_max_other_fraction"
            )
        return self


class MecrConfig(BaseModel):
    """Configuration for scoring spatial cell tables with MECR."""

    pair_id: str
    segmentation: str
    output_dir: Path
    samples: list[MecrSampleConfig]
    reference_markers_path: Path
    figure_dpi: int = Field(default=180, ge=72)
    barnyard_top_n_pairs: int = Field(default=6, ge=0)
    barnyard_max_points: int = Field(default=50_000, ge=100)
    barnyard_random_seed: int = Field(default=0, ge=0)
    barnyard_log1p: bool = False

    @model_validator(mode="after")
    def _validate_mecr_samples(self: MecrConfig) -> MecrConfig:
        if not self.samples:
            raise ValueError("MecrConfig requires at least one sample")
        return self


class MapMyCellsSampleConfig(BaseModel):
    """One clustered AnnData sample to annotate with MapMyCells."""

    sample_id: str
    platform: Literal["MERSCOPE", "XENIUM"]
    anndata_path: Path
    query_layer: str | None = "counts"
    gene_id_column: str | None = None
    obs_id_column: str | None = None


class MapMyCellsConfig(BaseModel):
    """Configuration for local MapMyCells cell type assignment."""

    pair_id: str
    output_dir: Path
    samples: list[MapMyCellsSampleConfig]
    reference_mode: Literal["whole_brain", "region", "both"] = "both"
    reference_atlas: Literal["whb", "wmb"] = "whb"
    query_species: Literal["human", "mouse"] = "human"
    auto_download_references: bool = True
    marker_lookup_path: Path | None = None
    precomputed_stats_path: Path | None = None
    gene_mapping_db_path: Path | None = None
    region_name: str = "frontal_a44_a45_a46_a32_acc"
    region_labels: list[str] = Field(
        default_factory=lambda: [
            "Human A44-A45",
            "Human A46",
            "Human A32",
            "Human ACC",
        ]
    )
    region_cache_dir: Path = Path("./mapmycells_cache")
    region_min_cells_per_leaf: int = Field(default=10, ge=1)
    region_force_rebuild: bool = False
    region_query_markers_n_per_utility: int = Field(default=10, ge=1)
    drop_level: str | None = None
    normalization: Literal["raw", "log2CPM"] = "raw"
    bootstrap_factor: float = Field(default=0.9, gt=0.0, le=1.0)
    bootstrap_iteration: int = Field(default=100, ge=1)
    n_processors: int = Field(default=4, ge=1)
    chunk_size: int | None = Field(default=None, ge=1)
    rng_seed: int | None = None
    max_gb: float | None = Field(default=None, gt=0.0)
    tmp_dir: Path | None = None
    cloud_safe: bool = False
    flatten: bool = False
    verbose_csv: bool = False
    plots_only: bool = False
    extra_args: list[str] = Field(default_factory=list)

    @field_validator("region_labels", mode="before")
    @classmethod
    def _parse_region_labels(cls: type[MapMyCellsConfig], value: Any) -> list[str]:
        if value is None:
            return []
        if isinstance(value, str):
            raw = value.strip()
            if not raw:
                return []
            if raw.startswith("["):
                import json

                parsed = json.loads(raw)
                if not isinstance(parsed, list):
                    raise ValueError("region_labels JSON must decode to a list")
                value = parsed
            else:
                return [part.strip() for part in raw.split(",") if part.strip()]
        if isinstance(value, list | tuple | set):
            return [str(item).strip() for item in value if str(item).strip()]
        raise ValueError("region_labels must be a list or comma-separated string")

    @field_validator("region_name")
    @classmethod
    def _validate_region_name(cls: type[MapMyCellsConfig], value: str) -> str:
        cleaned = value.strip()
        if not cleaned:
            raise ValueError("region_name must not be empty")
        return cleaned

    @model_validator(mode="after")
    def _validate_reference_inputs(self: MapMyCellsConfig) -> MapMyCellsConfig:
        if self.query_species == "mouse" and self.reference_atlas != "wmb":
            raise ValueError(
                "mouse MapMyCells queries currently require the WMB reference atlas"
            )
        if (
            not self.plots_only
            and self.reference_mode in {"whole_brain", "both"}
            and not self.auto_download_references
        ):
            if self.marker_lookup_path is None:
                raise ValueError(
                    "marker_lookup_path is required when automatic reference "
                    "downloads are disabled"
                )
            if self.precomputed_stats_path is None:
                raise ValueError(
                    "precomputed_stats_path is required when automatic reference "
                    "downloads are disabled"
                )
        if (
            not self.plots_only
            and self.reference_mode in {"region", "both"}
            and not self.region_labels
        ):
            raise ValueError(
                "region_labels must contain at least one Allen WHB ROI label when "
                "reference_mode includes region"
            )
        if (
            not self.plots_only
            and self.reference_atlas == "wmb"
            and self.query_species == "human"
            and self.gene_mapping_db_path is None
            and not self.auto_download_references
        ):
            raise ValueError(
                "gene_mapping_db_path is required for human-to-WMB mapping when "
                "automatic reference downloads are disabled"
            )
        if (
            not self.plots_only
            and self.reference_atlas == "wmb"
            and self.reference_mode in {"region", "both"}
            and any(label.lower().startswith("human ") for label in self.region_labels)
        ):
            raise ValueError(
                "WMB region_labels must be mouse region_of_interest_acronym values, "
                "not the default Human WHB labels"
            )
        if (
            self.reference_atlas == "wmb"
            and self.query_species == "human"
            and self.drop_level is None
        ):
            self.drop_level = "CCN20230722_SUPT"
        return self


class PipelineConfig(BaseSettings):
    """Top-level pipeline configuration, loadable from env vars."""

    output_root: Path = Path("./results")
    proseg_search_paths: list[Path] = [
        Path("/usr/bin/proseg"),
        Path("/usr/local/bin/proseg"),
    ]
    proseg_install_path: Path = Path("/usr/bin/proseg")
    proseg_auto_install: bool = True
    max_ram_gb: float = 600.0

    model_config = {"env_prefix": "MERXEN_"}


def load_config_from_json(path: Path, config_class: type[BaseModel]) -> BaseModel:
    """Load and validate a config from a JSON file.

    Args:
        path: Path to the JSON config file.
        config_class: The Pydantic model class to validate against.

    Returns:
        A validated config instance.
    """
    import json

    with open(path) as f:
        data = json.load(f)
    return config_class.model_validate(data)
